### ISSUE TITLE
Keeping track of our development roadmap!

### ISSUE THREAD

**Issue by Rishabh570** [publiclab/community-toolbox#141]
So far, we've made our project's structure to follow the MVC pattern, having a data layer (indexedDB). We've also reached our goal to show contributors' data repository-wise and optimised our code in order to save a considerable amount of requests while fetching recent contributors' data. However, we have a decent amount of things that need to be done still...they include,

- [ ] Refactoring our code (creating separate files for big functions, properly naming the files etc. etc.)
- [ ] Adding tests to the site
- [ ] Creating documentation that explains the flow of control (through a flowchart maybe)
- [ ] Notifying user about the unexpected errors
- [ ] Making API requests by keeping in check the remaining API quota
- [ ] Sorting the contributors' data according to their contributions (we can think of some other filters also)

These are the ideas that are known to my understanding till now, we need to discuss these and this issue can be used as a discussion thread! Appreciate any input :+1:

**Comment by Rishabh570** [comment]
@jywarren I've opened this issue to discuss our development roadmap :smiley: . I've listed things according to their priorities, top having the most priority! Is it appropriate?

**Comment by jywarren** [comment]
This looks awesome. It's also a great roadmap for others working on
different PL libraries! You should share in the weekly check in!

**Comment by Rishabh570** [comment]
Sure :)

**Comment by gauravano** [comment]
Hey @Rishabh570, nice checklist :+1:.

**Comment by Rishabh570** [comment]
@jywarren I want to implement these things (and #131 ) during my GSOC...should I add these in my draft?
Or, we need to discuss them first...?

**Comment by jywarren** [comment]
Hi @Rishabh570 thank you! I think you could open a proposal and we can discuss in there!
